CREATE TABLE "roadmap_skillRate" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roadmap_skillRate_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" varchar(256) NOT NULL,
	"technology" varchar(256) NOT NULL,
	"category" varchar(256) NOT NULL,
	"rating" integer NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "roadmap_technologies" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roadmap_technologies_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(256) NOT NULL,
	"category" varchar(256) NOT NULL,
	"description" text NOT NULL,
	"priority" integer NOT NULL,
	"createdAt" timestamp with time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
	"updatedAt" timestamp with time zone
);
--> statement-breakpoint
CREATE INDEX "user_id_idx" ON "roadmap_skillRate" USING btree ("userId");--> statement-breakpoint
CREATE INDEX "technology_idx" ON "roadmap_skillRate" USING btree ("technology");--> statement-breakpoint
CREATE UNIQUE INDEX "user_tech_category_unique_idx" ON "roadmap_skillRate" USING btree ("userId","technology","category");--> statement-breakpoint
CREATE INDEX "name_idx" ON "roadmap_technologies" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "name_category_unique_idx" ON "roadmap_technologies" USING btree ("name","category");